import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootProps {
  children: React.ReactNode
}

const RootLayout = ( { children, } : RootProps ) => {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </head> */}
      <body className={`${inter.className} bg-gray-100`}>
          <Nav />
          <div className="md:container mx-auto">
            {children}
          </div>
      </body>
    </html>
  )
}

export default RootLayout;